// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "GZHU",
            "email": "1065526695@qq.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/CloseSystem": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "结束返校 返回已结束返校状态码  对应状态为未| 1000-success、1039-失败",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "返校管理页面的接口"
                ],
                "summary": "关闭返校",
                "responses": {
                    "1000": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseMsg"
                        }
                    },
                    "1039": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseMsg"
                        }
                    }
                }
            }
        },
        "/api/DataInput": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "从终端上传excel文件  获取数据并去back_school表中查询后插入留校学生表中",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "multipart/form-data"
                ],
                "tags": [
                    "返校管理页面的接口"
                ],
                "summary": "导入留校名单",
                "parameters": [
                    {
                        "description": "name=",
                        "name": "excel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "学年 如：2022_2023",
                        "name": "year",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "学期",
                        "name": "semester",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "1000": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/mysql._ResponseGetStaySchoolList"
                        }
                    },
                    "1036": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/mysql._ResponseGetStaySchoolList"
                        }
                    }
                }
            }
        },
        "/api/DataOut": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "下载对应的数据导出 |||1--已返校，2--未返校，3--未申请 ||| 只需要访问请求对应的RRL就能在浏览器直接下载",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "返校管理页面的接口"
                ],
                "summary": "相应的数据导出 (支持全选传没选数据)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "是否全选，1--全选，0--未全选",
                        "name": "checked",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "类别，1--未返校，2--已返校，3--未申请",
                        "name": "category",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1000": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseGetStaySchoolList"
                        }
                    },
                    "1001": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseMsg"
                        }
                    }
                }
            }
        },
        "/api/DeleteAuth": {
            "post": {
                "description": "删除扫码权限，从数据表中删掉该行数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "返校应用相关接口"
                ],
                "summary": "删除扫码权限",
                "parameters": [
                    {
                        "description": "教职工工号",
                        "name": "staffID",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array"
                        }
                    },
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "userid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.RespSuccess"
                        }
                    }
                }
            }
        },
        "/api/DeleteTable": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除对应的学生留校表  ||||只是用来测试的时候方便建表后删表 --不用做请求--  测试时用postmen来删表 === 不需要做",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "multipart/form-data"
                ],
                "tags": [
                    "返校管理页面的接口"
                ],
                "summary": "删表",
                "parameters": [
                    {
                        "description": "学年 如：2022_2023",
                        "name": "year",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "学期",
                        "name": "semester",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "1020": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseMsg"
                        }
                    },
                    "1029": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseMsg"
                        }
                    }
                }
            }
        },
        "/api/Delete_StayStu": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "按输入的学号删除数据表中对应数据",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "multipart/form-data"
                ],
                "tags": [
                    "返校管理页面的接口"
                ],
                "summary": "删除留校学生名单",
                "parameters": [
                    {
                        "description": "学年 如：2022_2023",
                        "name": "year",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "学期",
                        "name": "semester",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "学号",
                        "name": "stu_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "1000": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/mysql._ResponseMsg"
                        }
                    },
                    "1020": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/mysql._ResponseMsg"
                        }
                    }
                }
            }
        },
        "/api/DownloadTem": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "下载导入留校学生名单的模板  |||| 只需要浏览器访问对应的RRL就能在浏览器直接下载",
                "tags": [
                    "返校管理页面的接口"
                ],
                "summary": "下载导入的模板",
                "responses": {}
            }
        },
        "/api/FailedDataDownload": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "下载导入失败的名单  |||| 只需要浏览器访问对应的RRL就能在浏览器直接下载",
                "tags": [
                    "返校管理页面的接口"
                ],
                "summary": "下载查询失败名单",
                "responses": {}
            }
        },
        "/api/GetAllData": {
            "get": {
                "description": "所有为空时加载",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "返校应用相关接口"
                ],
                "summary": "统计信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.RespStaInfo"
                        }
                    }
                }
            }
        },
        "/api/GetCollegeName": {
            "get": {
                "description": "获得学院名称列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "返校应用相关接口"
                ],
                "summary": "获得数据库中存在的所有学院信息列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "userid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.RespCollege"
                        }
                    }
                }
            }
        },
        "/api/GetStaySchoolList": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "展示留校学生表的数据",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "multipart/form-data"
                ],
                "tags": [
                    "返校管理页面的接口"
                ],
                "summary": "展示留校学生表所有名单",
                "parameters": [
                    {
                        "description": "学年 如：2022_2023",
                        "name": "year",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "学期",
                        "name": "semester",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "查询页数",
                        "name": "page",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "查询条数,默认：10条",
                        "name": "pagesize",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "1000": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/mysql._ResponseList"
                        }
                    },
                    "1001": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/mysql._ResponseMsg"
                        }
                    },
                    "1039": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/mysql._ResponseMsg"
                        }
                    }
                }
            }
        },
        "/api/InsertRowDemo": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "body带参数添加到数据库对应的表中",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "multipart/form-data"
                ],
                "tags": [
                    "返校管理页面的接口"
                ],
                "summary": "增添到留校学生表中",
                "parameters": [
                    {
                        "description": "学年 如：2022_2023",
                        "name": "year",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "学期",
                        "name": "semester",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "姓名",
                        "name": "stu_name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "学号",
                        "name": "stu_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "学院",
                        "name": "collegename",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "类别",
                        "name": "category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "年级",
                        "name": "grade",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "校区",
                        "name": "campus",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "状态",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "1000": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/mysql._ResponseMsg"
                        }
                    },
                    "1039": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/mysql._ResponseMsg"
                        }
                    }
                }
            }
        },
        "/api/JudgeConfirmPer": {
            "get": {
                "description": "加载时判断是否具有扫码权限,若有权限才可进入扫码界面，无权限则显示无权限提示",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "扫码相关接口"
                ],
                "summary": "判断是否具有扫码权限",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "userid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.RespSuccess"
                        }
                    }
                }
            }
        },
        "/api/ListOfReturneesDownload": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "不用做----||||只需要浏览器访问对应的RRL就能在浏览器直接下载",
                "tags": [
                    "导出应返校学生名单"
                ],
                "summary": "导出应返校学生名单",
                "responses": {}
            }
        },
        "/api/QueryStaff": {
            "post": {
                "description": "从教职工表中搜索教职工信息,状态码(1000-成功-对应搜索的数据返回)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "返校应用相关接口"
                ],
                "summary": "教职工搜索",
                "parameters": [
                    {
                        "description": "教职工工号/教职工姓名/页数/行数-后两个为int",
                        "name": "staffID/staffName/page/count",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "userid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.RespStaff"
                        }
                    }
                }
            }
        },
        "/api/Search": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "按输入的学号查询留校学生表",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "multipart/form-data"
                ],
                "tags": [
                    "返校管理页面的接口"
                ],
                "summary": "留校学生查询",
                "parameters": [
                    {
                        "description": "学年 如：2022_2023",
                        "name": "year",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "学期",
                        "name": "semester",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "查询的学号",
                        "name": "stu_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "查询的姓名",
                        "name": "stu_name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "1000": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseList"
                        }
                    },
                    "1032": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseMsg"
                        }
                    },
                    "1039": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseMsg"
                        }
                    }
                }
            }
        },
        "/api/SearchData": {
            "post": {
                "description": "设置筛选条件后调用，根据不同筛选条件返回数据，body里的参数如果不存在此筛选条件则设置为“”，例如校区只能传大学城，桂花岗和黄埔",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "返校应用相关接口"
                ],
                "summary": "统计信息--根据不同条件筛选",
                "parameters": [
                    {
                        "description": "校区(大学城，桂花岗，黄埔)/学生类别(本科、硕士、博士)/时间戳/如果没有此筛选条件则设置为‘’",
                        "name": "campus/studentType/backTime",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.RespStaInfo"
                        }
                    }
                }
            }
        },
        "/api/SetAuth": {
            "post": {
                "description": "设置扫码权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "返校应用相关接口"
                ],
                "summary": "扫码权限设置",
                "parameters": [
                    {
                        "description": "教职工工号/教职工姓名/校区（大学城，黄埔，桂花岗）",
                        "name": "staffID/staffName/staffCampus",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "userid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.RespSuccess"
                        }
                    }
                }
            }
        },
        "/api/ShowStaffInfo": {
            "post": {
                "description": "加载所有具有扫码权限的用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "返校应用相关接口"
                ],
                "summary": "显示权限用户",
                "parameters": [
                    {
                        "description": "页数/行数",
                        "name": "page/count",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "userid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.RespStaff"
                        }
                    }
                }
            }
        },
        "/api/Start_CreateTable": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "开启返校系统、新建数据表  返回开启返校状态码  对应状态为未| 1000-success、1039-失败",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "multipart/form-data"
                ],
                "tags": [
                    "返校管理页面的接口"
                ],
                "summary": "开启返校系统、新建留校学生表",
                "parameters": [
                    {
                        "description": "学年",
                        "name": "year",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "学期",
                        "name": "semester",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "1000": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseMsg"
                        }
                    },
                    "1039": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseMsg"
                        }
                    }
                }
            }
        },
        "/api/UpdateCampus": {
            "post": {
                "description": "修改校区",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "返校应用相关接口"
                ],
                "summary": "修改校区信息,参数按照括号内填写",
                "parameters": [
                    {
                        "description": "教职工工号/教职工校区（大学城、黄埔、桂花岗）",
                        "name": "staffID/staffCampus",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "userid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.RespSuccess"
                        }
                    }
                }
            }
        },
        "/api/WebBackPage": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返校管理页面  获取系统当前状态码   对应状态为未| 1027-已结束返校、1028-已开启返校",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "返校管理页面的接口"
                ],
                "summary": "返校管理页面  返回系统状态",
                "responses": {
                    "1027": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseMsg"
                        }
                    },
                    "1028": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseGetStaySchoolList"
                        }
                    }
                }
            }
        },
        "/api/datashow/:id": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "扫码后接收到学生学号显示学生信息接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "扫码相关接口"
                ],
                "summary": "显示学生信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseDataShow"
                        }
                    }
                }
            }
        },
        "/api/dataupdate": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "扫码后示确认学生返校的确认接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "扫码相关接口"
                ],
                "summary": "修改学生返校状态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseUpdateDate"
                        }
                    }
                }
            }
        },
        "/api/judgePermission": {
            "get": {
                "description": "加载时返回权限等级(1为超管，2为扫码权限人员，3为无权限人员)\"）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "返校应用相关接口"
                ],
                "summary": "判断权限等级",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "userid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.RespAuth"
                        }
                    }
                }
            }
        },
        "/api/msglist": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "调用用展示学生返校的几种情况\t获取 1- 未返校  2- 已返校  3- 未申请 的学生信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "展示相关接口"
                ],
                "summary": "展示学生返校情况",
                "parameters": [
                    {
                        "type": "string",
                        "example": "2020-09-01",
                        "description": "计划返校日期",
                        "name": "arrivalTime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "大学城",
                        "description": "校区",
                        "name": "campus",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "计算机",
                        "description": "学院",
                        "name": "collegeName",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2020",
                        "description": "年级",
                        "name": "grade",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "页号",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 10,
                        "description": "条数",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "姜",
                        "description": "姓名",
                        "name": "studentName",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2006100141",
                        "description": "学号",
                        "name": "studentNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "1- 已返校  2- 未返校  3- 未申请 的学生信息",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseMsgList"
                        }
                    }
                }
            }
        },
        "/create": {
            "post": {
                "description": "新增未返校的学生",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "新增未返校学生"
                ],
                "summary": "新增未返校学生",
                "parameters": [
                    {
                        "type": "string",
                        "example": "2022-09-01",
                        "description": "预计到达时间 “yyyy-mm-dd”传入",
                        "name": "except_arrival_time",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "2006100141",
                        "description": "学生学号",
                        "name": "student_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseUpdateDate"
                        }
                    }
                }
            }
        },
        "/home": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "使用本接口返回的地址作为该应用的请求地址！！",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "获取应用地址"
                ],
                "summary": "获取扫码应用请求地址",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseMsgList"
                        }
                    }
                }
            }
        },
        "/import": {
            "get": {
                "description": "读取excel文档导入返校码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "信息导入导出相关接口"
                ],
                "summary": "读取excel文档导入返校码",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseData"
                        }
                    }
                }
            }
        },
        "/msg/:id": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据学号去获取信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "展示相关接口"
                ],
                "summary": "根据学号去获取信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.RespSuccess"
                        }
                    }
                }
            }
        },
        "/web": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "使用本接口返回的地址作为该应用的请求地址！！",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "获取应用地址"
                ],
                "summary": "获取管理后台应用请求地址",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseMsgList"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.RespAuth": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "controller.RespCollege": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "controller.RespStaInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/service.NumOfStu"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "controller.RespStaff": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/mysql.RespStaffInfo"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "controller.RespSuccess": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "controller._ResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务响应状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据"
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "controller._ResponseDataShow": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务响应状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.StudentMsg"
                    }
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "controller._ResponseGetStaySchoolList": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务响应状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "controller._ResponseList": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务响应状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Stu"
                    }
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                },
                "totalQuery": {
                    "type": "integer"
                }
            }
        },
        "controller._ResponseMsg": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务响应状态码",
                    "type": "integer"
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "controller._ResponseMsgList": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务响应状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ShowStudentMsg"
                    }
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "controller._ResponseUpdateDate": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务响应状态码",
                    "type": "integer"
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "models.ShowStudentMsg": {
            "type": "object",
            "properties": {
                "arrival_time": {
                    "description": "预计返校时间",
                    "type": "string"
                },
                "college_name": {
                    "description": "学院名称",
                    "type": "string"
                },
                "grade": {
                    "description": "学生年级",
                    "type": "string"
                },
                "name": {
                    "description": "学生姓名",
                    "type": "string"
                },
                "scan_id": {
                    "description": "确认者id",
                    "type": "string"
                },
                "stu_status": {
                    "description": "返校状态",
                    "type": "integer"
                },
                "student_cps": {
                    "description": "学生所在校区",
                    "type": "string"
                },
                "student_num": {
                    "description": "学生学号",
                    "type": "integer"
                }
            }
        },
        "models.Stu": {
            "type": "object",
            "properties": {
                "campus": {
                    "description": "校区(本科生表)",
                    "type": "string"
                },
                "category": {
                    "description": "学生类别 (本科生或研究生)",
                    "type": "string"
                },
                "collegename": {
                    "description": "学院",
                    "type": "string"
                },
                "grade": {
                    "description": "年级",
                    "type": "string"
                },
                "name": {
                    "description": "姓名",
                    "type": "string"
                },
                "status": {
                    "description": "学生状态 (留校或未留校)",
                    "type": "string"
                },
                "stuid": {
                    "description": "学号",
                    "type": "string"
                }
            }
        },
        "models.StudentMsg": {
            "type": "object",
            "properties": {
                "college_name": {
                    "description": "学院名称",
                    "type": "string"
                },
                "grade": {
                    "description": "所在年级",
                    "type": "string"
                },
                "name": {
                    "description": "学生姓名",
                    "type": "string"
                },
                "student_cps": {
                    "description": "学生所在校区",
                    "type": "string"
                },
                "student_num": {
                    "description": "学生学号",
                    "type": "integer"
                }
            }
        },
        "mysql.RespCampus": {
            "type": "object",
            "properties": {
                "campus": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                }
            }
        },
        "mysql.RespCollege": {
            "type": "object",
            "properties": {
                "college": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                }
            }
        },
        "mysql.RespDegree": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "degree": {
                    "type": "string"
                }
            }
        },
        "mysql.RespStaffInfo": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mysql.StaffInfoStruct"
                    }
                }
            }
        },
        "mysql.StaffInfoStruct": {
            "type": "object",
            "properties": {
                "staffCampus": {
                    "description": "校区",
                    "type": "string"
                },
                "staffId": {
                    "description": "工号",
                    "type": "string"
                },
                "staffName": {
                    "description": "姓名",
                    "type": "string"
                },
                "staffOrg": {
                    "description": "部门",
                    "type": "string"
                }
            }
        },
        "mysql._ResponseGetStaySchoolList": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务响应状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "mysql._ResponseList": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务响应状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Stu"
                    }
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                },
                "result": {
                    "type": "integer"
                }
            }
        },
        "mysql._ResponseMsg": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务响应状态码",
                    "type": "integer"
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "service.NumOfStu": {
            "type": "object",
            "properties": {
                "numOfAll": {
                    "description": "应返校人数",
                    "type": "integer"
                },
                "numOfAllBack": {
                    "description": "已返校人数",
                    "type": "integer"
                },
                "numOfCampus": {
                    "description": "不同校区应返校人数",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mysql.RespCampus"
                    }
                },
                "numOfCampusBack": {
                    "description": "不同校区已返校人数",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mysql.RespCampus"
                    }
                },
                "numOfCollegeBack": {
                    "description": "不同学院返校人数",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mysql.RespCollege"
                    }
                },
                "numOfCollegeNotBack": {
                    "description": "不同学院未返校人数",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mysql.RespCollege"
                    }
                },
                "numOfStuType": {
                    "description": "不同学生类型应返校人数",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mysql.RespDegree"
                    }
                },
                "numOfStuTypeBack": {
                    "description": "不同学生类型已返校人数",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mysql.RespDegree"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "127.0.0.1",
	BasePath:         ":8080",
	Schemes:          []string{},
	Title:            "minipro文档",
	Description:      "小程序系统",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
